/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin-analytics'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AdminSkillDemandRouteImport } from './routes/admin-skill-demand'
import { Route as AdminTrainingProgressRouteImport } from './routes/admin-training-progress'
import { Route as AdminWorkforceCompetenciesRouteImport } from './routes/admin-workforce-competencies'
import { Route as AiAssessmentQuizRouteImport } from './routes/ai-assessment-quiz'
import { Route as BuildProfileRouteImport } from './routes/build-profile'
import { Route as CompetencyAssessmentRouteImport } from './routes/competency-assessment'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LearningPathsRouteImport } from './routes/learning-paths'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SkillGapAnalysisRouteImport } from './routes/skill-gap-analysis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin-analytics',
  path: '/admin-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSkillDemandRoute = AdminSkillDemandRouteImport.update({
  id: '/admin-skill-demand',
  path: '/admin-skill-demand',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrainingProgressRoute = AdminTrainingProgressRouteImport.update({
  id: '/admin-training-progress',
  path: '/admin-training-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkforceCompetenciesRoute =
  AdminWorkforceCompetenciesRouteImport.update({
    id: '/admin-workforce-competencies',
    path: '/admin-workforce-competencies',
    getParentRoute: () => rootRouteImport,
  } as any)
const AiAssessmentQuizRoute = AiAssessmentQuizRouteImport.update({
  id: '/ai-assessment-quiz',
  path: '/ai-assessment-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildProfileRoute = BuildProfileRouteImport.update({
  id: '/build-profile',
  path: '/build-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetencyAssessmentRoute = CompetencyAssessmentRouteImport.update({
  id: '/competency-assessment',
  path: '/competency-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPathsRoute = LearningPathsRouteImport.update({
  id: '/learning-paths',
  path: '/learning-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillGapAnalysisRoute = SkillGapAnalysisRouteImport.update({
  id: '/skill-gap-analysis',
  path: '/skill-gap-analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-skill-demand': typeof AdminSkillDemandRoute
  '/admin-training-progress': typeof AdminTrainingProgressRoute
  '/admin-workforce-competencies': typeof AdminWorkforceCompetenciesRoute
  '/ai-assessment-quiz': typeof AiAssessmentQuizRoute
  '/build-profile': typeof BuildProfileRoute
  '/competency-assessment': typeof CompetencyAssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/learning-paths': typeof LearningPathsRoute
  '/login': typeof LoginRoute
  '/skill-gap-analysis': typeof SkillGapAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-skill-demand': typeof AdminSkillDemandRoute
  '/admin-training-progress': typeof AdminTrainingProgressRoute
  '/admin-workforce-competencies': typeof AdminWorkforceCompetenciesRoute
  '/ai-assessment-quiz': typeof AiAssessmentQuizRoute
  '/build-profile': typeof BuildProfileRoute
  '/competency-assessment': typeof CompetencyAssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/learning-paths': typeof LearningPathsRoute
  '/login': typeof LoginRoute
  '/skill-gap-analysis': typeof SkillGapAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/admin-skill-demand': typeof AdminSkillDemandRoute
  '/admin-training-progress': typeof AdminTrainingProgressRoute
  '/admin-workforce-competencies': typeof AdminWorkforceCompetenciesRoute
  '/ai-assessment-quiz': typeof AiAssessmentQuizRoute
  '/build-profile': typeof BuildProfileRoute
  '/competency-assessment': typeof CompetencyAssessmentRoute
  '/dashboard': typeof DashboardRoute
  '/learning-paths': typeof LearningPathsRoute
  '/login': typeof LoginRoute
  '/skill-gap-analysis': typeof SkillGapAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-analytics'
    | '/admin-dashboard'
    | '/admin-skill-demand'
    | '/admin-training-progress'
    | '/admin-workforce-competencies'
    | '/ai-assessment-quiz'
    | '/build-profile'
    | '/competency-assessment'
    | '/dashboard'
    | '/learning-paths'
    | '/login'
    | '/skill-gap-analysis'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-analytics'
    | '/admin-dashboard'
    | '/admin-skill-demand'
    | '/admin-training-progress'
    | '/admin-workforce-competencies'
    | '/ai-assessment-quiz'
    | '/build-profile'
    | '/competency-assessment'
    | '/dashboard'
    | '/learning-paths'
    | '/login'
    | '/skill-gap-analysis'
  id:
    | '__root__'
    | '/'
    | '/admin-analytics'
    | '/admin-dashboard'
    | '/admin-skill-demand'
    | '/admin-training-progress'
    | '/admin-workforce-competencies'
    | '/ai-assessment-quiz'
    | '/build-profile'
    | '/competency-assessment'
    | '/dashboard'
    | '/learning-paths'
    | '/login'
    | '/skill-gap-analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSkillDemandRoute: typeof AdminSkillDemandRoute
  AdminTrainingProgressRoute: typeof AdminTrainingProgressRoute
  AdminWorkforceCompetenciesRoute: typeof AdminWorkforceCompetenciesRoute
  AiAssessmentQuizRoute: typeof AiAssessmentQuizRoute
  BuildProfileRoute: typeof BuildProfileRoute
  CompetencyAssessmentRoute: typeof CompetencyAssessmentRoute
  DashboardRoute: typeof DashboardRoute
  LearningPathsRoute: typeof LearningPathsRoute
  LoginRoute: typeof LoginRoute
  SkillGapAnalysisRoute: typeof SkillGapAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-analytics': {
      id: '/admin-analytics'
      path: '/admin-analytics'
      fullPath: '/admin-analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-skill-demand': {
      id: '/admin-skill-demand'
      path: '/admin-skill-demand'
      fullPath: '/admin-skill-demand'
      preLoaderRoute: typeof AdminSkillDemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-training-progress': {
      id: '/admin-training-progress'
      path: '/admin-training-progress'
      fullPath: '/admin-training-progress'
      preLoaderRoute: typeof AdminTrainingProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-workforce-competencies': {
      id: '/admin-workforce-competencies'
      path: '/admin-workforce-competencies'
      fullPath: '/admin-workforce-competencies'
      preLoaderRoute: typeof AdminWorkforceCompetenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assessment-quiz': {
      id: '/ai-assessment-quiz'
      path: '/ai-assessment-quiz'
      fullPath: '/ai-assessment-quiz'
      preLoaderRoute: typeof AiAssessmentQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-profile': {
      id: '/build-profile'
      path: '/build-profile'
      fullPath: '/build-profile'
      preLoaderRoute: typeof BuildProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competency-assessment': {
      id: '/competency-assessment'
      path: '/competency-assessment'
      fullPath: '/competency-assessment'
      preLoaderRoute: typeof CompetencyAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-paths': {
      id: '/learning-paths'
      path: '/learning-paths'
      fullPath: '/learning-paths'
      preLoaderRoute: typeof LearningPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-gap-analysis': {
      id: '/skill-gap-analysis'
      path: '/skill-gap-analysis'
      fullPath: '/skill-gap-analysis'
      preLoaderRoute: typeof SkillGapAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSkillDemandRoute: AdminSkillDemandRoute,
  AdminTrainingProgressRoute: AdminTrainingProgressRoute,
  AdminWorkforceCompetenciesRoute: AdminWorkforceCompetenciesRoute,
  AiAssessmentQuizRoute: AiAssessmentQuizRoute,
  BuildProfileRoute: BuildProfileRoute,
  CompetencyAssessmentRoute: CompetencyAssessmentRoute,
  DashboardRoute: DashboardRoute,
  LearningPathsRoute: LearningPathsRoute,
  LoginRoute: LoginRoute,
  SkillGapAnalysisRoute: SkillGapAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
